#############################################
# Check Parameters before staring
#############################################
exchange:
  bitbank:
    use: False
    api_key:
    api_secret:
  bitflyer:
    use: True
    api_key:
    api_secret:
  bitfinex:
    use: False
    api_key:
    api_secret:
  btcbox:
    use: False
    api_key:
    api_secret:
  coincheck:
    use: False
    api_key:
    api_secret:
  coinex:
    use: False
    api_key:
    api_secret:
  kraken:
    use: False
    api_key:
    api_secret:
  liquid:
    use: True
    api_key:
    api_secret:
  zaif:
    use: True
    api_key:
    api_secret:
logic:
  demo: True
  symbol: BTC/JPY
  open_margin: 0.001
  close_margin: 0.  # if you want not to close position, select None
  interval: 5
  force_close_position: False  # use op
notification:
  discord:
    webhook_url:       # How to get: https://note.mu/asim0613/n/n23073851a93c
  line:
    token:             # ref. https://notify-bot.line.me/ja/ , How to get: https://www.takeiho.com/python-line-bot
